<a href="https://colab.research.google.com/github/rumor-thrower/KU-Summer-SW-AI-Camp/blob/main/Numpy%20%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [105]:
import numpy as np

In [106]:
a = [1, 2, 3]
a

[1, 2, 3]

In [107]:
aa = list([1, 2, 3])
aa

[1, 2, 3]

In [108]:
type(a)

list

# 값을 만드는 3가지 방법

1. Literal (정해진 특수문자가 적다)
2. Instance
3. Factory Method

In [109]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [110]:
class A:
    def __repr__(self):
        return "repr"
    def __str__(self):
        return "str"

In [111]:
a = A()
a
# repr

repr

In [112]:
print(a)
# str

str


In [113]:
type(arr)

numpy.ndarray

In [114]:
zarr = np.zeros(3)
zarr

array([0., 0., 0.])

In [115]:
narr = np.array([[1, 2], [3, 4]])
print(narr)

[[1 2]
 [3 4]]


In [116]:
narr = np.array([[[1, 2, 3]], [[4, 5, 6]]])
narr

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [117]:
narr.shape

(2, 1, 3)

In [118]:
narr.dtype

dtype('int64')

# Python에서 수를 표현하는 4가지 방법

- 수의 최댓값은?

In [119]:
import sys

sys.maxsize
# 9223372036854775807

9223372036854775807

In [120]:
print(sys.maxsize + 1)
# 계산 가능, 단 메모리 추가 할당 필요!

9223372036854775808


In [121]:
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

In [122]:
max_float = sys.float_info.max
print(max_float == max_float + 1)
# True

True


In [123]:
print(0.1 + 0.1 + 0.1)
# 0.3 아님! (float - 부동소수점은 근삿값 사용)
# 0.30000000000000004

0.30000000000000004


AI의 경사하강법은 정답이 아니라 근삿값을 빠르게 구하는 것이 목표, float 자료형 사용!

In [124]:
int(True)
# 1

1

In [125]:
int(False)
# 0

0

Python, 나아가 Numpy의 정수형은 오버플로 無!

# Python에서 값을 보는 2가지 방법

1. repr (이름 호출)
2. str (print 함수 호출)

In [126]:
import tensorflow as tf

In [127]:
x = tf.constant([1, 2, 3])
x
# tf.Tensor([1 2 3], shape=(3,), dtype=int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [128]:
print(x)
# tf.Tensor([1 2 3], shape=(3,), dtype=int32)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [129]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [130]:
print(arr)
# [1 2 3]
# List와 혼동 우려!

[1 2 3]


In [131]:
arrX = np.array([1, 2, 3])
arrY = np.array([2, 4, 6])

arrX + arrY
# array([3, 6, 9])

array([3, 6, 9])

In [132]:
arr = np.array([1, 2, 3])
arr + 10
# array([11, 12, 13])
# 자동 브로드캐스팅!

array([11, 12, 13])

In [133]:
arrX = np.array([1, 2, 3])
arrY = np.array([2, 4])

arrX + arrY
# ValueError: operands could not be broadcast together with shapes (3,) (2,)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
arr = np.array([[1, 2]])
arr2 = np.array([[[1], [2]]])

print(arr.shape, arr2.shape)
# (1, 2) (1, 2, 1)

In [ ]:
arr + arr2
# array([[[2, 3],
#           [3, 4]]])

브로드캐스팅은 데이터 분석에서 자주 활용!

Python은 연산자가 내부 메소드로 실행!

In [ ]:
print(1 + 1 == (1).__add__(1))
# True

- 연산자 오버로딩: 연산자 기능 변경
- 다형성: 다른 자료형, 다른 기능

In [ ]:
setA = {1, 2, 3}
setB = {3, 4, 5}

setA & setB
# {3}

In [ ]:
setA - setB
# {1, 2}

- **행렬 곱**은 내적 연산들로 구성
- **내적**: 주변 환경을 고려해서 하나의 값으로 선형 축약
- **축약**(Reduction): 하나의 값으로 줄이기

In [ ]:
arrX = np.array([1, 2, 3])
arrY = np.array([2, 4, 6])

arrX * arrY

In [141]:
np.array?

In [ ]:
from scipy import signal

In [ ]:
arrX = np.array([1, 2, 3, 4, 5])
arrY = np.array([-1, 0, 1])

In [ ]:
signal.correlate?

In [ ]:
signal.correlate(arrX, arrY, "valid")

```
1, 2, 3, 4, 5
        -1, 0, 1
```

In [ ]:
signal.correlate(arrX, arrY, "full")

```
1, 2, 3, 4, 5
0, 0, -1, 0, 1
```

In [ ]:
tu = 1, 2
print(tu)
# (1, 2)

In [134]:
tu = 1,
print(tu)
# (1,)

(1,)


In [135]:
i = 1
print(i)
# 1

1


In [136]:
i = int(1)
print(i)
# 1

1


In [137]:
fst, snd = 1, 2
print(fst, snd)
# 1 2

1 2


In [138]:
fst, snd = 1, 2, 3
# ValueError: too many values to unpack (expected 2)

ValueError: too many values to unpack (expected 2)

In [ ]:
fst, *rest = 1, 2, 3
print(fst, rest)
# 1 [2, 3]

In [ ]:
print(*rest)
# 2 3

> NumPy 배열과 tf.Tensor의 가장 확연한 차이는 다음과 같습니다:
> - 텐서는 불변성(immutable)을 가집니다.

## 얕은 복사

In [139]:
li = [1, 2, 3]
copy = li[:]
print(copy)
# [1, 2, 3]

[1, 2, 3]


In [140]:
copy.append(4)
print(copy)
# [1, 2, 3, 4]
print(li)
# [1, 2, 3]
# 그대로(얕은 복사)!

[1, 2, 3, 4]
[1, 2, 3]


In [165]:
arr3d = np.arange(24).reshape(4, 6)
arr3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [166]:
arr3d[1][1]
# np.int64(7)

np.int64(7)

In [167]:
arr3d[1, 1]
# np.int64(7)

np.int64(7)

In [158]:
arr = np.array([1, 2, 3])
arr
# array([1, 2, 3])

array([1, 2, 3])

In [148]:
arr[0]
# np.int64(1)
# 인덱싱은 차원을 1 감소(2 -> 1)!

np.int64(1)

None 인덱싱은 오히려 차원을 1 증가!

In [172]:
arr[None]
# array([[1, 2, 3]])

array([[1, 2, 3]])

### 3차원 배열이니 ':' 2개 필요 (위에선 생략)

In [173]:
arr[None : :]
# array([[1, 2, 3]])

array([1, 2, 3])

In [174]:
arr[ : None :]
# array([[1, 2, 3]])

array([1, 2, 3])

In [175]:
arr[ : : None]
# array([[1, 2, 3]])

array([1, 2, 3])

### ... 으로 축약 가능

In [176]:
arr[None, ...]
# array([[1, 2, 3]])

array([[1, 2, 3]])

## 불리언 인덱싱

In [177]:
arr > 1
# array([False,  True,  True])

array([False,  True,  True])